package com.festivalapp.model;

public enum Role {
    ADMIN,
    FESTIVAL_DIRECTOR,
    FESTIVAL_MANAGER,
    PRODUCT_DESIGNER,
    TECHNICAL_SUPPORT,
    SALES_DIRECTOR,
    SALES_MANAGER,
    EVENT_ORGANIZER,
    MARKETING_MANAGER,
    BUYER,
    NEGOTIATION_MANAGER
}
